trunk-version = "^0.21.14"

[build]
target = "index.html"
dist = "dist"
public_url = "./"
inject_scripts = true
minify = "on_release"

[tools]
sass = "1.90.0"
wasm_bindgen = "0.2.100"
wasm_opt = "version_123"

[clean]
cargo = true
